server:
  port:  8280
spring:
  batch:
    initialize-schema: never
  jpa :
    hibernate:
      use-new-id-generator-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://10.5.30.84:13306/dev?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 180000
      connection-timeout: 30000
      validation-timeout: 5000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true


#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none #기존꺼 drop 후 table create
#    properties:
#      hibernate:
#        #        show_sql: true System.out 이므로 사용하지 않음
#        format_sql: true

logging.level:
  org.hibernateC:\Program Files\Java\jdk1.8.0_101.SQL: debug #log로 보여줌
  org.hibernate.type: trace #parameter value를 알려줌
